version: '3'

services:
  db:
    image: postgres:alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: full_stack_challenge
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - app-network
  backend:
    build: ./backend
    container_name: backend
    environment:
      APP_BACKEND_PORT: 3000
    command: bash -c "npm install && npm start"
    volumes:
      - ./backend:/srv/app/backend
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - db
networks:
  app-network:
    driver: bridge