version: '3'

services:
  db:
    image: postgres:alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: full_stack_challenge
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - app-network
  backend:
    build: ./backend
    container_name: backend
    environment:
      APP_BACKEND_PORT: 3000
    command: bash -c "npm run up"
    volumes:
      - ./backend:/srv/app/backend
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - db
  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      APP_FRONTEND_PORT: 4200
    command: bash -c "npm install && npm start"
    volumes:
      - ./frontend:/srv/app/frontend
    ports:
      - 4200:4200
    networks:
      - app-network
networks:
  app-network:
    driver: bridge